In [1]:
import pandas as pd

In [2]:
data_movies = pd.read_csv("data/movies.csv")
data_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10000 non-null  int64
 1   title         10000 non-null  object
 2   overview      10000 non-null  object
 3   genre_ids     10000 non-null  object
 4   popularity    10000 non-null  float64
 5   release_date  9998 non-null   object
 6   poster_path   9993 non-null   object
 7   vote_average  10000 non-null  float64
 8   vote_count    10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [3]:
data_movies.head()

,id,title,overview,genre_ids,popularity,release_date,poster_path,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]",41.8985,1994-09-23,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,8.709,28228
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]",34.4570,1972-03-14,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,8.686,21399
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]",14.8922,1974-12-20,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,8.570,12927
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]",43.5047,1993-12-15,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,8.564,16402
4,389,12 Angry Men,The defense and the prosecution have rested an...,[18],14.7159,1957-04-10,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,8.548,9102

In [27]:
data_movies["genre_ids"]

0               [18, 80]
1               [18, 80]
2               [18, 80]
3        [18, 36, 10752]
4                   [18]
              ...
9995        [28, 14, 80]
9996                [35]
9997            [27, 53]
9998                [35]
9999    [28, 12, 14, 18]
Name: genre_ids, Length: 9992, dtype: object

In [28]:
data_genres = pd.read_csv("data/genres.csv")

In [33]:
data_genres

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [34]:
from ast import literal_eval

In [35]:
a = zip(data_genres["id"], data_genres["name"])

In [36]:
a

In [37]:
genre_dict = dict(a)

In [38]:
genre_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [39]:
data_movies["genres"] = data_movies["genre_ids"].apply(lambda x: ",".join([genre_dict.get(genre_id, "Unknown") for genre_id in x]))

In [40]:
data_movies["genre_ids"]

0               [18, 80]
1               [18, 80]
2               [18, 80]
3        [18, 36, 10752]
4                   [18]
              ...
9995        [28, 14, 80]
9996                [35]
9997            [27, 53]
9998                [35]
9999    [28, 12, 14, 18]
Name: genre_ids, Length: 9992, dtype: object

In [41]:
type(data_movies["genre_ids"][0])

str

In [42]:
data_movies["genre_ids"] = data_movies["genre_ids"].apply(lambda x: literal_eval(x))

In [43]:
type(data_movies["genre_ids"][0])

list

In [44]:
data_movies["genres"] = data_movies["genre_ids"].apply(lambda x: ",".join([genre_dict.get(genre_id, "Unknown") for genre_id in x]))

In [46]:
data_movies["genres"]

0                          Drama,Crime
1                          Drama,Crime
2                          Drama,Crime
3                    Drama,History,War
4                                Drama
                     ...
9995              Action,Fantasy,Crime
9996                            Comedy
9997                   Horror,Thriller
9998                            Comedy
9999    Action,Adventure,Fantasy,Drama
Name: genres, Length: 9992, dtype: object

In [47]:
data_movies = pd.read_csv("data/movies.csv")

In [48]:
import ast
genre_dict = dict(zip(data_genres["id"], data_genres["name"]))

def convert_genre_ids(genre_id_str):
    if isinstance(genre_id_str, str):
        genre_ids = ast.literal_eval(genre_id_str)
    else:
        genre_ids = genre_id_str

    return ",".join([genre_dict.get(genre_id, "Unknown") for genre_id in genre_ids])

data_movies["genres"] = data_movies["genre_ids"].apply(convert_genre_ids)

In [49]:
data_movies.head()

,id,title,overview,genre_ids,popularity,release_date,poster_path,vote_average,vote_count,genres
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]",41.8985,1994-09-23,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,8.709,28228,"Drama,Crime"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]",34.4570,1972-03-14,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,8.686,21399,"Drama,Crime"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]",14.8922,1974-12-20,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,8.570,12927,"Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]",43.5047,1993-12-15,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,8.564,16402,"Drama,History,War"
4,389,12 Angry Men,The defense and the prosecution have rested an...,[18],14.7159,1957-04-10,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,8.548,9102,Drama

In [50]:
data_movies.isnull().sum()

id              0
title           0
overview        0
genre_ids       0
popularity      0
release_date    2
poster_path     7
vote_average    0
vote_count      0
genres          0
dtype: int64

In [51]:
data_movies = data_movies.dropna()

In [52]:
data_movies.isnull().sum()

id              0
title           0
overview        0
genre_ids       0
popularity      0
release_date    0
poster_path     0
vote_average    0
vote_count      0
genres          0
dtype: int64

In [53]:
data_movies.duplicated(subset=["id", "title"]).sum()

np.int64(0)

In [54]:
data_movies.to_csv("data/movies_converted.csv", index=False)